### ISSUE TITLE
Square root not taken for euclidean distance in kmedians clustering

### ISSUE THREAD

**Issue by ramkashyap-s** [annoviko/pyclustering#325]
Distance is calculated by calling "euclidean_distance_sqrt". But, I think "euclidean_distance" should be used, because in  "euclidean_distance_sqrt", the distance is just squared but the square root is not taken. In "euclidean_distance" square root is taken.

**Comment by annoviko** [comment]
Hello, @ramkashyap-s 

Thank you for your suggestion. Square distance is used to have the best performance - because in this case we do not need to get square root. I would like to underline that algorithms use such representation only in implementation and it is not visible to end-user and such approach does not affect final clustering results.
