### ISSUE TITLE
Kmedoids returns incorrect number of clusters

### ISSUE THREAD

**Issue by aalloul** [annoviko/pyclustering#366]
Hi, 

I'm currently trying to use the kmedoids implementation of pyclustering and I have the feeling I stumbled upon a bug. Here is a description for a data frame I'm trying to cluster with 3 medoids:

```
from pyclustering.cluster import kmedoids
# Initialise with 3 clusters
initial_medoid_indices = [707, 1129, 692]
cluster_algo = kmedoids.kmedoids(df.as_matrix(), initial_medoid_indices, 0.1)
# where df is a pandas dataframe, df.shape returns (1177, 8)
cluster_algo.process()
clusters = get_clusters()
```
Checking the length of clusters, I find it's only 2 lists inside instead of 3. So instead of returning 3 clusters, the library returned 2.

I also wrapped my code in a while loop that only exits if the number of clusters returned is equal to 3. And I had the following output:
```
Attempt number 1
INFO:Clustering:Trying to find some initialization parameters
INFO:Clustering: Initialization done
INFO:Clustering:Trying to find some initialization parameters
 Found number of clusters = 2
INFO:Clustering: Initialization done
Attempt number 2
INFO:Clustering:Trying to find some initialization parameters
 Found number of clusters = 1
INFO:Clustering: Initialization done
Attempt number 3
 Found number of clusters = 3
```
It took 3 attempts (re-initialising everything at every step) to get the right number of clusters. The 2 following attempts, returned 2 clusters.

My environment:
 - Python 3.6.1
 - pyclustering version 0.6.6
 - pandas 0.20.3
 - latest MAC OS X

The question is to know whether this is indeed a bug or whether I'm doing something wrong?

**Comment by annoviko** [comment]
Hello, @aalloul,

Thank you very much for the reporting, I guess you are right - it is a bug, because medoid is a index of real point and in the worse case cluster will consists at least one object (point) - because this point is a medoid.

I have already found place in the implementation where bug is located. And I would like to ask you to share data with me that was used for clustering. Could you please provide it?

**Comment by aalloul** [comment]
Thank you for your super quick reply @annoviko, very much appreciated!

I had to anonymise the data and put it in a github repo (can't find a way to attach anything to this issue). The link is https://github.com/aalloul/clustering_data/blob/master/data.csv

Please let me know if I can be of any help.

**Comment by annoviko** [comment]
@aalloul , thank you for the provided data, it really helps me to identify error in the algorithm.

I have introduced correction for the problem to the branch **0.7.dev** (rev. https://github.com/annoviko/pyclustering/commit/071b3ec27b4270156224b7a6e7e5e004bdfd9f49).

There is code example, that demonstrates that algorithm works correctly (I have saved the provided data to simple text file 'data_in_text_file.txt'):
```python
from pyclustering.cluster.kmedoids import kmedoids;
from pyclustering.utils import read_sample;


sample = read_sample("data_in_text_file.txt");

start_medoids = [104, 345, 123];
kmedoids_instance = kmedoids(sample, start_medoids);

kmedoids_instance.process();
clusters = kmedoids_instance.get_clusters();

# Before, 2 clusters were extracted
print("Amount of clusters:", len(clusters));
for cluster in clusters:
    print("Cluster length:", len(cluster));
```

Root cause of the problem: in case of data where a lot of totally similar points there is high probability to choose medoids that corresponds to point that are totally similar, so algorithm omitted one of them.

**Comment by annoviko** [comment]
@aalloul , in case of your data, result highly depends on initial medoids. In this case it's much better to use K-Means algorithm with K-Means++ initialization method. K-Means++ is not available in 0.6.6, but it is implemented in 0.7.dev (0.7 version haven't been released yet). You can take 'master' or '0.7.dev' branch of pyclustering for that purpose. Here is an example of usage K-Means with K-Means++ initialization:
```python
from pyclustering.utils import read_sample;

from pyclustering.cluster.kmeans import kmeans;
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer;

sample = read_sample("data_in_text_file.txt");
centers = kmeans_plusplus_initializer(sample, 3).initialize();

kmeans_instance = kmeans(sample, centers);
kmeans_instance.process();
clusters = kmeans_instance.get_clusters();

print("Amount of clusters:", len(clusters));
for cluster in clusters:
    print("Cluster length:", len(cluster));
```

Output in this case (data distribution between clusters looks better than in case of K-Medoids):
```bash
Amount of clusters: 3
Cluster length: 672
Cluster length: 93
Cluster length: 412
```

**Comment by aalloul** [comment]
Hi @annoviko 

thank you for the fix and advices provided! 

I agree with you, the data I have is not good enough. I need to modify some of the features and add others that are more descriptive of the outcome I'm looking for.

I like the advice about k-Means++ initialization, thanks a lot!

Adam.

**Comment by annoviko** [comment]
@aalloul , you're welcome!
