### ISSUE TITLE
k-medioids with custom distance

### ISSUE THREAD

**Issue by suwangcompling** [annoviko/pyclustering#417]
I am new to pyclustering. Rummaging through the source code I didn't see how I could insert custom distance (either by passing a callable that computes pairwise distance or a precomputed distance matrix). Could you help? Thanks.

To be more specific, the following is the sort of thing I'm talking about:
```
import numpy as np
from scipy.cluster.hierarchy import linkage, fcluster

def my_dist(u,v): # exemplifying using a weird distance metric.
    return (u + v).sum()

data = np.array([[1,2,3,4],
                 [5,6,7,8]])
clust = linkage(data, method='average', metric=my_dist)
prediction = fcluster(clust, 2, criterion='maxclust')
```

**Comment by annoviko** [comment]
Hello, @suwangcompling,

You are correct about metrics. Currently, it is not possible to change them, by default Euclidean distance is used for calculation. I will add feature to use user-defined metric or predefined metrics for k-medoids algorithm.

**Comment by annoviko** [comment]
@suwangcompling, general metric are implemented in module 'pyclustering.utils.metric', metric usage (include user-defined) is supported for k-medoids for python and C/C++ parts of the library.

Here is several code examples how to create distance metric:
```python
metric = distance_metric(type_metric.EUCLIDEAN);
distance = metric([1.0, 2.5], [-1.2, 3.4]);
```

```python
user_function = lambda point1, point2: point1[0] + point2[0] + 2;
metric = distance_metric(type_metric.USER_DEFINED, func=user_function);
distance = metric([2.0, 3.0], [1.0, 3.0]);
```

And here is an example how to use for K-Medoids:
```python
from pyclustering.utils.metric import type_metric, distance_metric;

# create Minkowski distance metric with degree equals to '2'
metric = distance_metric(type_metric.MINKOWSKI, degree=2);

# create K-Medoids algorithm with specific distance metric
kmedoids_instance = kmedoids(sample, initial_medoids, metric=metric);

# run cluster analysis and obtain results
kmedoids_instance.process();
clusters = kmedoids_instance.get_clusters();
```

Changes are available on branch '0.8.dev' and will be available in the next release - 0.8.1.

**Comment by suwangcompling** [comment]
Thanks. This is helpful!

**Comment by annoviko** [comment]
I have just merged it to 'master' branch, so you can get it from 'master' branch also.

**Comment by xunhs** [comment]
> @suwangcompling, general metric are implemented in module 'pyclustering.utils.metric', metric usage (include user-defined) is supported for k-medoids for python and C/C++ parts of the library.
> 
> Here are several code examples how to create distance metric:
> 
> ```python
> metric = distance_metric(type_metric.EUCLIDEAN);
> distance = metric([1.0, 2.5], [-1.2, 3.4]);
> ```
> 
> ```python
> user_function = lambda point1, point2: point1[0] + point2[0] + 2;
> metric = distance_metric(type_metric.USER_DEFINED, func=user_function);
> distance = metric([2.0, 3.0], [1.0, 3.0]);
> ```
> 
> And here is an example how to use metric in K-Medoids:
> 
> ```python
> from pyclustering.utils.metric import type_metric, distance_metric;
> 
> # create Minkowski distance metric with degree equals to '2'
> metric = distance_metric(type_metric.MINKOWSKI, degree=2);
> 
> # create K-Medoids algorithm with specific distance metric
> kmedoids_instance = kmedoids(sample, initial_medoids, metric=metric);
> 
> # run cluster analysis and obtain results
> kmedoids_instance.process();
> clusters = kmedoids_instance.get_clusters();
> ```
> 
> Changes are available on branch '0.8.dev' and will be available in the next pyclustering release - 0.8.1.

that seems to work just for kmedoids method, 

`user_function = lambda point1, point2: point1[0] + point2[0] + 2
metric = distance_metric(type_metric.USER_DEFINED, func=user_function)
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)
kmedoids_instance = kmedoids(data=sample, initial_index_medoids=[2,3], metric=metric)

kmedoids_instance.process()
clusters = kmedoids_instance.get_clusters()`

but **fail to run kmeans**, like that:

`user_function = lambda point1, point2: point1[0] + point2[0] + 2
metric = distance_metric(type_metric.USER_DEFINED, func=user_function)
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)
start_centers = [[0.2, 0.1], [4.0, 1.0]]
kmeans_instance = kmeans(data=sample,
                            initial_centers = start_centers,
                            metric=metric)

kmeans_instance.process()
clusters = kmeans_instance.get_clusters()`
i'm new to pyclustering. Thanks for ur help.

**Comment by annoviko** [comment]
@xunhs , the problem is corrected, see https://github.com/annoviko/pyclustering/issues/471 .

**Comment by PabloBotas** [comment]
I just wanted to note that the *user_function* here given as example is not very illustrative of what an actual function should look like for *k-means*.

`user_function = lambda point1, point2: point1[0] + point2[0] + 2;`

This function will work, but it doesn't explain what the signature and expected capabilities of the function are. I found while trying to implement an actual function (in python) that *point1*, *point2* were arrays, not always of the same size. I ended up using *numpy*'s broadcasting abilities to easily circumvent the issue.

The example is a bit convoluted because in this particular case the *x,y* coordinates have a very different meaning than the *z* coordinate, so the input arrays must be sliced the get the arrays we want. Then two intermediate distance results are calculated and used to calculate a total distance. I am not explicitly writing the implementation of the haversine distance, but keep the broadcasting in mind when implementing your desired function.

The result looked something like:

```{python}
def d_metric(points1, points2):
    ### Pyclustering needs nested arrays here.
    if not isinstance(points1, np.ndarray):
        points1 = np.array(points1)
    if not isinstance(points2, np.ndarray):
        points2 = np.array(points2)
    ### Unpack desired slices with coords and ppp
    p1 = points1[...,:1]
    p2 = points2[...,:1]
    lat1 = points1[...,1:2]
    lat2 = points2[...,1:2]
    lon1 = points1[...,2:3]
    lon2 = points2[...,2:3]
    ### Get distances and return total
    d_g = haversine_distance(lat1, lat2, lon1, lon2)
    d_p = np.absolute(p1-p2)
    return np.sqrt(np.square(d_g) + np.square(d_p))
```

I hope this helps the next one trying something similar, and, please, let me know if I am wrong and this could be done in a much simple way.

**Comment by PabloBotas** [comment]
Great, happy to help and thanks a lot for your package!

**Comment by david-cortes** [comment]
Any chance of making it accept a pre-computed matrix (ideally triangular part only) with arbitrary distances?

**Comment by hangshuaibi** [comment]
Hello, I want to know whether there is any way to specify the number of cluster of `kmedoids`,  or it's determined in run-time, thanks!

**Comment by dsmccormick8492** [comment]
Maybe I don't understand your question, but you implicitly set the number
of clusters by the  initial_index_medoids parameter: the number of items
(indexes) you send to that determine the number of medoids you get back
after invoking process() function.

from the examples in the documentation:

from pyclustering.cluster.kmedoids
<https://pyclustering.github.io/docs/0.9.3/html/de/dfd/namespacepyclustering_1_1cluster_1_1kmedoids.html>
import kmedoids
from pyclustering.cluster
<https://pyclustering.github.io/docs/0.9.3/html/d1/d2a/namespacepyclustering_1_1cluster.html>
import cluster_visualizer
from pyclustering.utils
<https://pyclustering.github.io/docs/0.9.3/html/da/d28/namespacepyclustering_1_1utils.html>
import read_sample
from pyclustering.samples.definitions import FCPS_SAMPLES
# Load list of points for cluster analysis.
sample = read_sample
<https://pyclustering.github.io/docs/0.9.3/html/da/d28/namespacepyclustering_1_1utils.html#ac745f830ff5e61ef90a9b4eeeee1ea06>
(FCPS_SAMPLES.SAMPLE_TWO_DIAMONDS)
# Set random initial medoids.
initial_medoids = [1, 500]
# Create instance of K-Medoids algorithm.
kmedoids_instance = kmedoids(sample, initial_medoids)
# Run cluster analysis and obtain results.
kmedoids_instance.process()
kmedoids = kmedoids_instance.get_medoids()

You will get 2 medoids back since initial_medoids had two indexes.

see
https://pyclustering.github.io/docs/0.9.3/html/d0/dd3/classpyclustering_1_1cluster_1_1kmedoids_1_1kmedoids.html
for
the details.

David

**Comment by dsmccormick8492** [comment]
...you could set the number of medoids you want and set
initial_medoids_index to some random sample (without replacement) of the
indexes to the medoid data points. Something like this:

from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.cluster import cluster_visualizer
from pyclustering.utils import read_sample
from pyclustering.samples.definitions import FCPS_SAMPLES

import numpy as np

MEDOID_COUNT = 3 # number of medoids you want

# Load list of points for cluster analysis.
sample = read_sample(FCPS_SAMPLES.SAMPLE_TWO_DIAMONDS)

# Set random initial medoids.
medoid_indexes = len(sample)
initial_medoid_indexes = np.random.choice(medoid_indexes,
size=MEDOID_COUNT, replace=False)

# Create instance of K-Medoids algorithm.
kmedoids_instance = kmedoids(sample, initial_medoid_indexes)
# Run cluster analysis and obtain results.
kmedoids_instance.process()
kmedoids = kmedoids_instance.get_medoids()

for medoid_index in kmedoids:
    print(sample[medoid_index])
