### ISSUE TITLE
k-Medoids with non-symmetric distance matrix

### ISSUE THREAD

**Issue by attack68** [annoviko/pyclustering#418]
I intend on using k-medoids for a large dataset. Many of the points are replicated in the dataset, so the dataset is collapsed to tuples of distinct points and their respective counts.

As a reference to the type of matrix operations I intend consider "Bauckhage, Christian. (2015). NumPy / SciPy Recipes for Data Science: k-Medoids Clustering. 10.13140/2.1.4453.2009."

For my large dataset, however, it is redundant to have, say, 10k identical points (at X) referencing another 5k identical points (at Y) with a distance 1 between them, and 1k points at Z with distance 2 to both X and Y. Instead the distance metrix is better characterised by suggesting a medoid at any center has zero to its replicants but factors the count of the other groups. That is we have for distance measured from medoid at row to datapoint at column:

        X      Y      Z      
    X  0      5000   2000
    Y  10000  0      2000
    Z  20000  10000  0

I do not think that this type of redundancy removal is available in this package but you may be interested in the suggestion if you allow a 'precomputed' distance matrix to be provided to the k-medoids algorithm. If you have any comments I'd love to read them!

The type of analysis is textual where multiple items appear thousands of times.

**Comment by annoviko** [comment]
Hello, @attack68,

I guess it is usefull feature because I have already had similar request to introduce usage of distance matrix in DBSCAN and OPTICS algorithms (see issue #412) and both already have such feature (available on 'master' branch and will be available in 0.8.1 version). I would like to say thank you for your proposal, never hesitate propose ideas if you have them. I will introduce feature to use distance matrix in K-Means, K-Medoids, K-Medians and X-Means algorithms.

Some words about distance matrixes and big data. Of course, algorithm's performance is increased due to pre-calculated distance matrix - it reduces usage of distance metric calculation, especially when Euclidean or Minkowski metric is used or when input data is described in high-dimensional space. But, if we are talking about really big data then distance matrix is not a panacea because of memory consumption. Distance matrix consumes O(n^2) memory and it is a problem that restrics usage of such approach. For example, if you have data with 100.000 points then distance matrix will have following size: 100.000 * 100.000 * 8 bytes = 80.000.000.000 bytes = 80 Gbytes. I think it's too much for RAM, even for SSD if some RAM chunks (related to distance matrix) will be placed on HDD. In case of common HDD (not SSD), access operation can be greater than distance calculation in CPU. Thus, from my point of view, distance matrix is useful in case slightly big data.

**Comment by annoviko** [comment]
@attack68,
Feature to support distance matrix for K-Medoids algorithm is done. But matrix should be symmetric. In other words, non-symetric matrix should be converted to symmetric, for example, using 'dist = min(d(x, y), d(y, x))', or, for example, average: 'dist = (d(x, y) + d(y, x)) / 2.0'.

Here is an usage example:
```python
# calculate distance matrix for sample
sample = read_sample(path_to_sample);
matrix = calculate_distance_matrix(sample);

# create K-Medoids algorithm for processing distance matrix instead of points
kmedoids_instance = kmedoids(matrix, initial_medoids, data_type='distance_matrix');

# run cluster analysis and obtain results
kmedoids_instance.process();

clusters = kmedoids_instance.get_clusters();
medoids = kmedoids_instance.get_medoids();
```

The changes are available on '0.8.dev' and 'master' branches. If you are going to use version from repository you need to build ccore manually, for example, in case of linux
```bash
cd pyclustering/ccore
make ccore_x64 # in case 64-bit version
```

In case of 32-bit version:
```bash
make ccore_x86
```

This feature will be available in the next pyclustering release - 0.8.1.

**Comment by zahs123** [comment]
@annoviko  how do i get calculate_distance_matrix?

**Comment by annoviko** [comment]
@zahs123 , calculate_distance_matrix belongs to utils:
```python
from pyclustering.utils import calculate_distance_matrix
```
