### ISSUE TITLE
Save model SOM

### ISSUE THREAD

**Issue by nguyenkhacthanh** [annoviko/pyclustering#456]
Model net SOM can not save by pickle, Python throw exception ValueError ctypes objects containing pointers cannot be pickled

**Comment by annoviko** [comment]
Hello, @nguyenkhacthanh ,

Thank you for your report, I will provide solution to resolve this problem.

**Comment by annoviko** [comment]
@nguyenkhacthanh ,

Requested feature is implemented. Now it is possible to store and load network using pickle. Changes are available on branch '0.8.dev'. If you take it from repository then you need to rebuilt core (C++ part of pyclustering library). Otherwise only Python implementation will be used, but anyway it is possible to use pickle. Here is instruction how to build core: https://github.com/annoviko/pyclustering/wiki/Core-of-the-PyClustering

Here is an example where SOM is stored and loaded using pickle:
```Python
import pickle
from pyclustering.nnet.som import som, type_conn
from pyclustering.utils import read_sample
from pyclustering.samples.definitions import SIMPLE_SAMPLES

sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE1)
network = som(1, 2, type_conn.grid_four)
network.train(sample, 100)

dump_network = pickle.dumps(network)
network = pickle.loads(dump_network)
```

**Comment by nguyenkhacthanh** [comment]
@annoviko thank you

**Comment by annoviko** [comment]
I have merged changes to 'master' branch, so you can obtain them from 'master' branch as well.
