### ISSUE TITLE
'The pyclustering core is not supported for platform 'darwin' (64bit)'

### ISSUE THREAD

**Issue by ruifengma** [annoviko/pyclustering#481]
When I was using pyclustering to do K-medoids clustering and I got this issue, I'm currently using the macOS system

**Comment by annoviko** [comment]
Hello, @ruifengma,
The problem is that I cannot support this platform carefully because of lack MAC OS environment. Therefore in case of MAC OS python implementation used instead of C++. Currently, C++ implementation is supported for Linux and Windows. I have plans to support C++ implementation of the library for MAC OS, but they are block by no access to MAC OS platform even on Virtual Box (probably hackintosh will be suitable for that purpose?).

**Comment by ruifengma** [comment]
Hello, @annoviko ,
Thanks for your kindly reply

**Comment by annoviko** [comment]
MacOS is going to be supported in release 0.9.0 (issue: #486).
