### ISSUE TITLE
XMeans - Always produces kmax clusters

### ISSUE THREAD

**Issue by lutrasdebtra** [annoviko/pyclustering#488]
I'm trying to use the `xmeans` algorithm. However, it always produces `kmax` clusters. Despite my plotting showing heavy similarity between clusters. I've tried modifying `tolerance` with a multitude of values (0.0, 0.0000001, 0.00125, 0.025, 0.5, 1.0, 5.0, 100.0, 1000.0), but the algorithm always produces `kmax clusters`.

Additionally, increasing `kmax` to a huge value (like 100), results in a 100 clusters, where some clusters might be created from as little as 0.1% of the dataset. 

Is this the expected behaviour? It seems to me `tolerance` is not working correctly.

**Comment by annoviko** [comment]
Hello, @lutrasdebtra,
May I ask you to show the code of your program?

**Comment by lutrasdebtra** [comment]
I've made a small test notebook with shows the issue [here](https://drive.google.com/open?id=1u2157qvifArDY8T8jrOCPB24Oa3sYXKn), you can find the `training_data.csv` [here](https://drive.google.com/open?id=1IJv-UOerwOSrO1mQrgtct4dSMF61wuIq). 

If you run the notebook you'll notice many of the clusters have fairly minor variations, so I'd like to avoid treating them as separate clusters.

**Comment by annoviko** [comment]
@lutrasdebtra, thank you for the code and data, I will check it.

**Comment by annoviko** [comment]
@lutrasdebtra, I have dug a little into your problem. About tolerance, it affects only K-Means, but K-Means always make at least one step and this algorithm converges really fast, just a few steps. In other words, tolerance does not affect X-Means that uses K-Means algorithm. X-Means algorithm divides initial cluster into two and then performs cluster analysis using K-Means among points that belong to the initial cluster. Then it estimates clusters (in your case BIC) and if estimation is better than for the initial cluster then the initial is split into two. Moreover, results that can be obtained by X-Means and K-Means depends on initial centers.

X-Means well-tested and well-covered by unit and integration tests as well as K-Means. I have check clustering process using a debugger and algorithm works properly. Most probably estimator is not suitable. I have tried MNDL estimator, but it looks like it also not suitable.

I have tried to visualize your data, but it is a trivial task for matplotlib - too many points, but it looks like an elongated cluster, but I not sure because I have checked several dimensions only. So if you are sure that K-Means can be suitable then probably Elbow algorithm will be useful. I have tried to use Elbow algorithm to estimate the amount of cluster and it shows that data contains 4 clusters:
```python
import pandas as pd
import matplotlib.pyplot as plt

from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.elbow import elbow
from pyclustering.cluster.kmeans import kmeans
from pyclustering.cluster.encoder import cluster_encoder, type_encoding

#plt.style.use("ggplot")

df_training = pd.read_csv('training_data.csv', quotechar='\'')


def create_figures(sample, clusters, centers, main_name=''):
  encode = cluster_encoder(kmeans_instance.get_cluster_encoding(), clusters, sample)
  encode.set_encoding(type_encoding.CLUSTER_INDEX_LABELING)
  encoded_labels = encode.get_clusters()
  total_size = len(encoded_labels)

  plt.figure(figsize=(20,30))
  plt.suptitle(main_name)
  per_line = 4
  for i,center in enumerate(centers):
      plt.subplot(len(clusters)/per_line+1,per_line,i+1)
      plt.plot([x/2. for x in range(48)], [i*100 for i in center])
      plt.title("Cluster {} ({}% - {})".format(i, round(encoded_labels.count(i)/total_size*100.0, 2), encoded_labels.count(i)))
      plt.ylim(0,100)
      plt.xlim(0,24)
      plt.show()

sample = df_training.values

elbow_instance = elbow(sample, 1, 21)
elbow_instance.process()
amount = elbow_instance.get_amount()
print("Amount of clusters:", amount)

initializer = kmeans_plusplus_initializer(sample, amount)
initial_centers = initializer.initialize()

kmeans_instance = kmeans(sample, initial_centers)
kmeans_instance.process()
clusters = kmeans_instance.get_clusters()
centers = kmeans_instance.get_centers()

create_figures(sample, clusters, centers)
```

And following result I have obtained:
![1](https://user-images.githubusercontent.com/6785869/51758076-edb9a400-20d5-11e9-807c-b7cb2afaf929.png)
![2](https://user-images.githubusercontent.com/6785869/51758077-edb9a400-20d5-11e9-9b10-86d51654d900.png)
![3](https://user-images.githubusercontent.com/6785869/51758079-ee523a80-20d5-11e9-90fd-ae196d55df50.png)
![4](https://user-images.githubusercontent.com/6785869/51758080-ee523a80-20d5-11e9-9e98-04f70968466d.png)

Is it expected result?

**Comment by lutrasdebtra** [comment]
Thanks for the extensive dive into the data. When using `KMeans`, I generally expect between 4 and 8, but those look like the major clusters that I've seen previously. 

For context, each row of the data is individual days of energy meter, so each cell corresponds to a 30 minute measurement (48 per day). I've fuzzed the data (so it's not indicative of real consumers), but these are the general trends expected. 

I've been using KMeans previously, but wanted to try and see if XMeans could give me similar clusters to  make sure I wasn't missing anything in the data.
