### ISSUE TITLE
DBSCAN with user defined metric

### ISSUE THREAD

**Issue by lukanovak93** [annoviko/pyclustering#582]
Hi, I see there are options for k-means and k-medians top ass user-defined metric for clustering algorithm to work with. Is there a plan to add this option to DBSCAN algorithm?

**Comment by annoviko** [comment]
Hi @lukanovak93 ,

There were such plans, but the problem is that DBSCAN depends on KD-Tree and there are a lot of work to do to support this feature. 

But be aware that you can calculate distance matrix using any metric and then provide the matrix to DBSCAN. Here is an example:
```python
from pyclustering.samples.definitions import SIMPLE_SAMPLES
from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.dbscan import dbscan
from pyclustering.utils import read_sample, calculate_distance_matrix, type_metric, distance_metric

# load list of points for cluster analysis
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)

# create distance matrix using Manhattan metric
matrix = calculate_distance_matrix(sample, metric=distance_metric(type_metric.MANHATTAN))

# Run cluster analysis using DBSCAN
dbscan_instance = dbscan(sample, 0.5, 3)
dbscan_instance.process()

# visualize clustering results
visualizer = cluster_visualizer()
visualizer.append_clusters(dbscan_instance.get_clusters(), sample)
visualizer.show()
```

**But still, there is one problem**. And there are some optimizations regarded to Euclidean distance. And if your distance metric is going to be completely different from Euclidean than there are might be problem with proper cluster allocation because DBSCAN scan expects Euclidean space and Euclidean metric when it operates with `eps`.

I will put this task to backlog, but I am not sure that I will be able to release it in the next release `pyclustering 0.10.0`.

**Comment by lukanovak93** [comment]
Ok, I understand. The problem is my distance matrix could potentially be to large to compute and keep in memory. But I understand your point. Thanks for the reply :)
