### ISSUE TITLE
process() stops without explanation when medoid initial indices are out of range 

### ISSUE THREAD

**Issue by lorenzznerol** [annoviko/pyclustering#604]
If I use 
from pyclustering.cluster.kmedoids import kmedoids
samples = [some list of arrays, the list has a length of 8]
initial_medoids = [1, 5, 8] (randomly chosen)
kmedoids_instance = kmedoids(samples, initial_medoids)
kmedoids_instance.process() will stop the script and make forget all of the variables

There is no explanation that the script stops because of wrongly chosen initial_medoids indices.

kmedoids_instance.process() will create a nullpointer and stop. No explanation was given that the index 8 is out of range. Instead, all of the variables in memory are lost after this and the script cannot be tested any further without a full restart, and it took me some time to find out the small mistake. Of course, index 7 is the highest possible index if you have 8 samples and I know that. First, I was new to this clustering method and I did not even know that the indices of the medoids are indexes for the samples and not indexes inside the sample arrays, and thus I did not know that I had to align the max index with the length of the samples list, and second, it is not explained clearly that the length of the initial_medoids determine the final number of clusters, at least when I believe this post: 

https://stackoverflow.com/questions/56978613/how-to-use-kmedoids-from-pyclustering-with-set-number-of-clusters

Quote: "It is true you can control the number of cluster, which correspond to the length of initial_medoids.
The documentation is not clear about this. The get__clusters function "Returns list of medoids of allocated clusters represented by indexes from the input data". so, this function does not return the cluster labels. It returns the index of rows in your original (input) data."

**Comment by annoviko** [comment]
Hi @lorenzznerol ,

Thank you for your feedback. The biggest problem that python code calls C++ code in order to get maximum performance and if an exception occurs then its description is not delivered to the python code. There are some checks on a creation step, but I agree it is not enough.

There are already issues that cover this problem: #592 and #591.

I hope I will be able to find a time to finish these two tasks soon, or probably someone else will contribute to pyclustering in order to resolve these tasks.
