### ISSUE TITLE
k-medoids clustering with multivariate distance matrices

### ISSUE THREAD

**Issue by laurenleesc** [annoviko/pyclustering#618]
I'm attempting to cluster observations based on two separate strings of words from two different categories. I have created two separate distance matrices for each group of words using the Jaccard Distance. Is it possible to use the pyclustering k-medoids routine to cluster with multiple distance matrices? Something like:

kmedoids_instance=kmedoids(dist_matrix1, dist_matrix2, initial_medoids, data_type='distance_matrix')

I cannot see how to revert back to non-distance matrix data, since my variables are strings of words for comparison.

Thanks in advance!

**Comment by annoviko** [comment]
Hello @laurenleesc ,

I am sorry, but `kmedoids` does not support more than one distance matrix that is considered as an input data that should be clustered. Two matrices sound like two inputs, is it enough to cluster each matrix separately and then merge them?

Because right now it is unclear for me what kind of output should be in this case? And how to operate with these matrices?

**Comment by laurenleesc** [comment]
Hello @annoviko ,

Thank you for your reply. 

The two distance matrices are from two variables for the same dataset, analogous to the multivariate iris data. The difference is, since the two variables are word sets, they do not exist in a coordinate space, so I cannot back up a step to the input data -set as a non-distance matrix. So for your second suggestion, I can indeed cluster each matrix separately and then merge them but do you have any suggestions for how to merge them?

Thank you for your reply.

Lauren

**Comment by annoviko** [comment]
Hello @laurenleesc ,

I think it depends on your particular task, so I cannot give you an advise how to merge them.
